import "./globals.css";
import type { Metadata } from "next";
import Texture from "@/components/Texture";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Texture />
        {children}
      </body>
    </html>
  );
}
